{{- if and .Values.monitoring.enabled .Values.monitoring.prometheusRule.enabled .Values.monitoring.prometheusRule.rules }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "symphony.fullname" . }}
  labels:
    {{- include "symphony.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ include "symphony.fullname" . }}
      rules:
        {{- with .Values.monitoring.prometheusRule.rules }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
