{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "symphony.fullname" . }}
  labels:
    {{- include "symphony.labels" . | nindent 4 }}
type: Opaque
data:
  linear-api-key: {{ .Values.secrets.linearApiKey | b64enc | quote }}
{{- end }}
